feat(helm): create charts for deployment
kilnfi/eth-validator-watcher pull request #51
Opened 2023-06-27 16:20 UTC by cebidhem

2023-07-20 15:05 UTC, nalepae requested changes

2023-07-20 15:05 UTC, nalepae commented on Dockerfile
> +FROM gcr.io/distroless/python3:debug
should be `nonroot`

2023-08-17 08:52 UTC, MattKetmo commented on charts/eth-validator-watcher/values.yaml
> +  - 0x81f455f55c701997fa64bfdbbe707e058e4d2d971e6d5dbfd5a276a03e1ce822825739f418421bfee4a7d6dd55fe10e3
is it expected to have keys on default values?

2023-08-17 13:53 UTC, MattKetmo approved these changes

2023-08-17 13:56 UTC, merged